import { NextRequest, NextResponse } from 'next/server'
import OpenAI from 'openai'

// Mock response for demo/testing
const generateMockArticle = (topic: string, keywords: string) => {
  return `# ${topic}

## Introduction

${topic} is a crucial aspect of modern digital marketing that every business should understand. In this comprehensive guide, we'll explore the key strategies and best practices that can help you succeed.

## Key Benefits

When implementing ${topic} strategies, businesses typically see:

• Increased organic traffic and visibility
• Better search engine rankings
• Higher conversion rates
• Improved user engagement
• Cost-effective marketing results

## Best Practices

### 1. Research and Planning
Start with thorough keyword research focusing on terms like ${keywords || 'relevant industry keywords'}. Understanding your target audience is essential for creating content that resonates.

### 2. Content Optimization
Create high-quality, valuable content that addresses your audience's pain points. Focus on:
- Clear, engaging headlines
- Well-structured content with proper headings
- Internal and external linking strategies
- Mobile-friendly formatting

### 3. Technical Implementation
Ensure your website is technically optimized for search engines:
- Fast loading speeds
- Mobile responsiveness
- Clean URL structure
- Proper meta tags and descriptions

## Advanced Strategies

For businesses looking to take their ${topic} efforts to the next level, consider:

• Long-tail keyword targeting
• Content clustering and topic authority
• Local SEO optimization
• Voice search optimization
• Featured snippet optimization

## Measuring Success

Track these key metrics to measure your ${topic} performance:
- Organic traffic growth
- Keyword ranking improvements
- Click-through rates
- Conversion rates
- Time on page and bounce rate

## Conclusion

Implementing effective ${topic} strategies requires consistent effort and ongoing optimization. By following these best practices and staying updated with the latest trends, you can achieve significant improvements in your online visibility and business growth.

Remember to regularly analyze your performance and adjust your strategy based on data-driven insights. Success in ${topic} is a marathon, not a sprint.

---

*This article was generated by BlogCraft AI in under 60 seconds. Generate unlimited SEO-optimized content for your business at blogcraft-ai.com*`
}

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
})

export async function POST(request: NextRequest) {
  try {
    const { topic, keywords } = await request.json()

    if (!topic) {
      return NextResponse.json(
        { error: 'Topic is required' },
        { status: 400 }
      )
    }

    // Check if using demo API key
    if (process.env.OPENAI_API_KEY?.includes('demo') || !process.env.OPENAI_API_KEY?.startsWith('sk-')) {
      console.log('Using mock API response for demo')
      const article = generateMockArticle(topic, keywords)
      return NextResponse.json({ article })
    }

    const keywordText = keywords ? `Focus on these keywords: ${keywords}` : ''
    
    const prompt = `Write a comprehensive, SEO-optimized blog post about "${topic}".

Requirements:
- 800-1200 words
- Include an engaging title
- Use proper heading structure (H1, H2, H3)
- Write in a conversational, engaging tone
- Include actionable tips and insights
- Optimize for search engines
- ${keywordText}

Structure:
1. Compelling title
2. Introduction that hooks the reader
3. Main content with subheadings
4. Conclusion with key takeaways

Make it valuable, informative, and easy to read.`

    const completion = await openai.chat.completions.create({
      model: "gpt-3.5-turbo",
      messages: [
        {
          role: "system",
          content: "You are an expert SEO content writer who creates engaging, optimized blog posts that rank well on Google."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      max_tokens: 2000,
      temperature: 0.7,
    })

    const article = completion.choices[0]?.message?.content

    if (!article) {
      throw new Error('Failed to generate article')
    }

    return NextResponse.json({ article })
  } catch (error) {
    console.error('Error generating article:', error)
    
    // Fallback to mock response if API fails
    const { topic, keywords } = await request.json()
    const article = generateMockArticle(topic, keywords)
    
    return NextResponse.json({ 
      article,
      note: 'Demo mode - using mock response. Add real OpenAI API key for AI generation.'
    })
  }
}