import { NextRequest, NextResponse } from 'next/server'
import { stripe } from '@/lib/stripe'

export async function POST(request: NextRequest) {
  try {
    const { userId, userEmail, priceId = 'price_founder_999' } = await request.json()

    if (!userId || !userEmail) {
      return NextResponse.json(
        { error: 'User ID and email are required' },
        { status: 400 }
      )
    }

    // Check if using demo Stripe keys
    if (process.env.STRIPE_SECRET_KEY?.includes('demo') || !process.env.STRIPE_SECRET_KEY?.startsWith('sk_')) {
      console.log('Demo mode: Simulating Stripe checkout')
      return NextResponse.json({ 
        sessionId: 'demo_session_id',
        url: '/dashboard?demo_payment=success',
        note: 'Demo mode - payment simulation'
      })
    }

    const session = await stripe.checkout.sessions.create({
      mode: 'subscription',
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'inr',
            product_data: {
              name: 'BlogCraft AI - Founder Special',
              description: 'Unlimited SEO-optimized blog posts generated by AI',
            },
            unit_amount: 99900, // ₹999 in paise
            recurring: {
              interval: 'month',
            },
          },
          quantity: 1,
        },
      ],
      success_url: `${process.env.NEXT_PUBLIC_APP_URL}/dashboard?session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: `${process.env.NEXT_PUBLIC_APP_URL}/signup`,
      customer_email: userEmail,
      metadata: {
        userId,
      },
      allow_promotion_codes: true,
      billing_address_collection: 'required',
    })

    return NextResponse.json({ sessionId: session.id, url: session.url })
  } catch (error) {
    console.error('Stripe checkout error:', error)
    return NextResponse.json(
      { error: 'Failed to create checkout session' },
      { status: 500 }
    )
  }
}